---
abstract: 'clean imports from package-exporting modules'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  constant: 0
  perl: 5.011002
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.011002
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lexical-Import
provides:
  Lexical::Import:
    file: lib/Lexical/Import.pm
    version: 0.002
requires:
  Carp: 0
  Lexical::Var: 0.006
  Module::Runtime: 0.011
  Params::Classify: 0
  XSLoader: 0
  perl: 5.011002
  strict: 0
  version: 0.81
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
